### ISSUE TITLE
Mass Alerts: Toggle parameters in mass alert when Constant Size checked

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#105]
Related to the new values for size and density in #96, the changing mass alerts will describe density of mass rather than size of mass when the Constant Size check box is checked.

Examples are straight from design doc: [Changing mass alerts](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.ce5d7rlnapb8)
Mass increases to 3 billion kg:
- With Constant Size Not checked:
  - {{3}} billion kilograms. As {{mass gets bigger}} force arrows {{get bigger}}, forces now {{force-value-newtons Newtons}}.
- With Constant Size checked:
  - {{3}} billion kilograms. As {{density increases}} force arrows {{get bigger}}, forces now {{force-value-newtons Newtons}}.

Mass decreases to 1 billion kg:
- With Constant Size Not checked
  - {{1}} billion kilograms. As {{mass gets smaller}} force arrows {{get smaller}}, forces now {{force-value-newtons Newtons}}.
- With Constant Size checked:
  - {{1}} billion kilograms. As {{density decreases}} force arrows {{get smaller}}, forces now {{force-value-newtons Newtons}}.

@zepumph, please note that I re-arranged the brackets to include the word "mass" as it is not in the mass alert that describes density.

**Comment by terracoda** [comment]
@zepumph, let me know if you need more examples.

**Comment by zepumph** [comment]
In the above commits I added support for "density increases/decreases" alerts to replace the "mass gets bigger/smaller" alerts. For the most part it was straight forward. 

Side note about the implementation:
I updated the central function for getting "gets bigger" or "gets smaller" to support "mass gets bigger" and the other. This then made it easy to check there and swap out the whole phrase, including "mass", for "density increases". The only weirdness is that this function is used by other functions responsible for creating the edge case alerts specific to mass, like "as mass gets bigger and moves right". This isn't a problem because these edge cases are never hit, but it is a bit tricky if there is a bug, because it could display something like "density increases and moves right." One such bug I found and tracked down to https://github.com/phetsims/inverse-square-law-common/commit/43a1919a07428d67f0a8d1c24dfac3cec9fd8b1e looked very strange indeed!

@terracoda please review, and keep you eyes peeled for sneaky bugs like "as density increase and moves right".

**Comment by terracoda** [comment]
@zepumph, I am about to verify your implementation.

I just had a thought, is it possible to check for edge cases only if Constant Size is not check, in other words stop checking for edge cases when Constant Size is indeed checked?

**Comment by terracoda** [comment]
@zepumph, the implementation seems to be working well. I am happy to close this issue, but before I do, I just want to ask, do you think it would be more robust to split up the main function to handle edge mass-moving edge cases into a separate function, one where the model would 
> check for edge cases only if Constant Size is not check, in other words stop checking for edge cases when Constant Size is indeed checked?

**Comment by zepumph** [comment]
@terracoda this is sorta happening already, but it is a bit more complicated. We have a methods like:

```js
    getMassValueChangedAlertText( objectEnum ) {

// default that could be mass or density
      let massClause = this.massDescriber.getMassOrDensityChangeClause( objectEnum );

// NOTE: this is separate logic for only if there were edge cases
      // if changing the mass of an object caused one of the masses to move position
      if ( this.model.massWasPushed() ) {
        massClause = this.massDescriber.getMassChangesAndMovesClause( objectEnum );
        if ( this.model.pushedObjectEnumProperty.value !== objectEnum ) {
          massClause = this.massDescriber.getMassChangesAndMovesOtherClause( objectEnum );
        }
      }
```

The key weirdness is that all three of these massDescriber functions end up using the same shared approach for getting the mass/density wording, but in the bottom two cases, it will always return the mass piece because the parameters are being checked here before calling the function. Closing

**Comment by zepumph** [comment]
In the above commits, also note that I renamed a function for clarity, and removed a bunch of duplicated logic between GFLBAlertManager and GravityForceLabAlertManager by making the BASICS one extend from REGULAR.
