### ISSUE TITLE
Mass Control Alerts says masses are moving when they are not

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#132]
Just noticed when changing mass, I got the moving mass alerts incorrectly.

The description of moving the other sphere on a mass change also fires incorrectly, but I didn't take a screen shot of the other one.

I can't seem to easily reproduce the incorrect alerts.
<img width="707" alt="Screen Shot 2019-05-20 at 1 55 33 PM" src="https://user-images.githubusercontent.com/1902116/58020066-602c1500-7b07-11e9-8087-04e8101fd183.png">

We have had this bug before. I'm not sure when it re-appeared, but I do know that it also happened during my session on May 10th with the latest described version that is sonified.

**Comment by terracoda** [comment]
I noticed this while verifying #125, but as I said this bug also appeared on May 19th with a previous version.

**Comment by terracoda** [comment]
@zepumph, I think these edge-case alerts were originally verified in https://github.com/phetsims/gravity-force-lab-basics/issues/90

I'm not sure when issues crept back in, but I don't think I heard them before May 10th.

**Comment by zepumph** [comment]
@terracoda I made two changes here.
1. The state of the mass alert is now reset (it wasn't before). Likely the weirdness had to do with this if you were trying to read the alert after reset.
2. I made the alert more "in sync" with the mass Property changing. Before there was a delay because the position wasn't updated until after the mass change listeners had already changed. I tried to summarize as best I could in https://github.com/phetsims/gravity-force-lab/commit/811313bb43b1c6e315dbf2af6518ae85c1bf0e37#diff-362d7004dfabf9a253530b2ff4189675R93. 

The fix was to link to the position dependent Property from the mass listener, so that there was a direct link, and the description could be updated in the next frame once position updates. 

Tagging @jessegreenberg because this solution relies heavily on `ValueChangeUtterance`. Basically, when  the case occurs where a mass changes pushes an object, we alert an incorrect Utterance in one frame, as well as attaching a listener such that when the position is changed in the next frame, the correct Utterance will be alerted. Since they are both alerted as the same instance of a ValueChangeUtterance, one will seamless overwrite the other. I didn't encounter any issues here, but it seems a bit weird so I thought I'd mention it.

@terracoda these alerts should now be totally fixed, and if they aren't I'd love to hear about it! =) 
Sorry about the confusion last time this bug came up.

**Comment by terracoda** [comment]
@zepumph, the mass alerts sound good, unassigning myself. @jessegreenberg, please close after you review.

**Comment by jessegreenberg** [comment]
This seems like a valid use case of Utterance `alertStableDelay`, my only concern is that this in this usage seems like it works around a model implementation detail.

Could the strategy be changed to only generate the correct description when we detect one of the two cases? What I am wondering about is if ISLCObjects had something like 
`valueChangedPositionConstantEmitter` and `valueChangedPositionChangedEmitter`, each one emitting from the various cases in `ISLCModel.step()`. `alertMassValueChanged` would be added as a listener to these rather than the `valueProperty` directly.

I haven't thought through it very carefully, and understand that this may not be doable, but wanted to throw it out for consideration.

**Comment by zepumph** [comment]
Yes that makes a lot of sense. An emitter cleaned things up nicely in the alert manager, though it added some code to the model step function. Please review with the following thoughts:
* I needed to add a conditional around each positionProperty/valueChangedPositionEmitter pair because before one was being called each frame, and Property.set() was providing the no-op. Adding the Emitter meant I had to add the no-op to this level in the code.
* I needed to repeat the emitter emit as many times as the positionProperty was changed in cases. This is a bit lame, but fine with me overall.
* I really like what happened to GravityForceLabAlertManager.

**Comment by zepumph** [comment]
The above commit fixes the alerts, Now we know (a) which object's value changed AND (b) which object's position changed. The alert changes for all 4 cases there.

**Comment by zepumph** [comment]
The above commit fixes the alerts, Now we know (a) which object's value changed AND (b) which object's position changed. The alert changes for all 4 cases there.

**Comment by jessegreenberg** [comment]
Cool, looks great! I am personally OK with the points in https://github.com/phetsims/gravity-force-lab-basics/issues/132#issuecomment-497829426 and given how they make it easier to observe the model changes we are interested in.
