### ISSUE TITLE
Mass getting bigger, but VO says Force Arrows are getting smaller.

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#151]
This issue could be related to #132, but maybe not.

When mass spheres are closest to each other and you increase the mass, the alert is:
> As mass gets bigger and moves mass 2 right, force arrows get smaller, forces now {N} newtions.

However, the _force_ is getting bigger, so the _force arrows_ should also be getting bigger.

**Here are some screen shots:**
<img width="487" alt="2-billion" src="https://user-images.githubusercontent.com/1902116/59667202-9fa55a00-91b6-11e9-874d-831a59ae3256.png">
<img width="493" alt="3-billion" src="https://user-images.githubusercontent.com/1902116/59667208-a2a04a80-91b6-11e9-87aa-918db2bb3c0f.png">
<img width="507" alt="5-billion" src="https://user-images.githubusercontent.com/1902116/59667215-a633d180-91b6-11e9-9509-08750942c606.png">
<img width="504" alt="9-billion" src="https://user-images.githubusercontent.com/1902116/59667226-ab911c00-91b6-11e9-9442-73eb862f7231.png">

**But it doesn't happen all the time:**
<img width="499" alt="Screen Shot 2019-06-18 at 10 30 17 AM" src="https://user-images.githubusercontent.com/1902116/59667306-c5326380-91b6-11e9-986a-4a5928d2e7bf.png">

@zepumph, I think this is new. I don't remember seeing/hearing this bigger/smaller conflict before.

**Comment by terracoda** [comment]
Also happens sometimes when one mass sphere has a maxxed position and the same sphere is moving as mass is changed.
<img width="523" alt="Screen Shot 2019-06-18 at 10 54 04 AM" src="https://user-images.githubusercontent.com/1902116/59667834-b1d3c800-91b7-11e9-8eaa-f8aa5fe15e23.png">
<img width="539" alt="Screen Shot 2019-06-18 at 11 03 05 AM" src="https://user-images.githubusercontent.com/1902116/59668779-5c98b600-91b9-11e9-8648-413f1febc24f.png">

If I start with the sphere smallest and closest and just increase mass 2, 
- I get the incorrect bigger/smaller alerts at 3, , 4, 5, 7, , 9 billion kg and 
- the correct bigger/bigger alerts at 6, 8, and 10 billion kg.

The same thing happens if I have mass 1 at left edge, mass 2 closest to mass 1, and then change the mass of mass 1:
- I get the incorrect bigger/smaller alerts at 2, 3, 4, 5, 7, , 9 billion kg and 
- the correct bigger/bigger alerts at 6, 8, and 10 billion kg.

@zepumph, I noticed visually **that the said mass sphere does not actually move at 6, 8, and 10 billion kilograms when we get the correct alert**, so maybe there is a distance value that needs to be adjusted, or there is some kind of rounding error? The force values on the screen are getting bigger whether the spheres move or not, so the description should match whether the sphere visually moves or not. It is just an artifact of the snap-to grid that the spheres do not actually move on some steps.

**Comment by zepumph** [comment]
Ugh this is such a good bug!! The issue is that we recently set up Utterances to overwrite their previous alerts, and only alert the last item once it has become "stable." This is to help with the spamming of the queue. Here we are doing just that:

*  Move the masses to touch (no alert)
*  Increase one of the masses
* This increases the force
* this sends an alert to the queue like "forces get bigger"
* On the NEXT frame ( .17ms later), the position changes, bumping one of the masses away to the grid.
* This decreases the force
* This alerts another utterance to the queue like " forces get smaller" because they did this time.
* The new alert overwrites the old one, which was not sent to aria-live because it had not yet become "stable" (it would have needed 1000ms to be stable).
* We only hear the second alert.

I want to talk to @jessegreenberg about this order of ops problem.

**Comment by zepumph** [comment]
@jessegreenberg helped me out greatly with this. It turns out that we can pass an override through in the case where the model/position causes the alert. In that case we ALWAYS know that the mass got bigger, so we can hard code that to use the "gets bigger" string. @terracoda please review. Does it seem fixed to you?

**Comment by terracoda** [comment]
That bug was such a surprise.
Awesome pairing work, all looks good to me. Thanks @jessegreenberg and @zepumph!
