### ISSUE TITLE
Mass strings are tiny

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-force-lab-basics#172]
Latest dev (dev.43), published 7/31/19

![image](https://user-images.githubusercontent.com/8419308/64460834-bd4cd600-d0b8-11e9-92a7-794518039121.png)

master
![image](https://user-images.githubusercontent.com/8419308/64460868-d2296980-d0b8-11e9-9f59-99cbce26ab83.png)

My guess is that the shrunken strings are an unintended consequence of some other change to the code. The size in dev.43 is definitely preferred @zepumph.

**Comment by zepumph** [comment]
Oops! This occurred because of work done in https://github.com/phetsims/gravity-force-lab/issues/76 to consolidate the label and its shadow into one PhET-iO instrumented item. Further design discussion in https://github.com/phetsims/gravity-force-lab/issues/175 will result in the removal of the shadow text, and the addition of a stroke. I'll commit the fix shortly.

**Comment by zepumph** [comment]
This will be covered generally as part of https://github.com/phetsims/inverse-square-law-common/issues/79. Closing
