### ISSUE TITLE
On IpadOS VO fails to read out "closest" alert or "extremely close" alert

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/gravity-force-lab-basics#185]
**Test device**
IPad 6th Gen
**Operating System**
IpadOS 13
**Browser**
Safari
**Problem description**
From https://github.com/phetsims/QA/issues/441

Looks like  https://github.com/phetsims/gravity-force-lab-basics/issues/183#issuecomment-541943443 and was missed on last RC test for IPad. Went back and checked last version and found same behavior.

When using VO on IPadOS 13, attempting to move the spheres any closer to each other after the closest possible distance has been reached will simply cause VO to read out the current distance and fail to read out "closest" or "extremely close".

**Steps to reproduce**
1. Set both mass values equal to 1
2. Check the constant size box
3. Adjust the sliders so that the spheres are as close as possible to each other
4. Attempt to move the spheres any closer together

**Comment by zepumph** [comment]
@loganbraywork two questions:

* Does this happen on master?
* Does this happen with other devices?

**Comment by loganbraywork** [comment]
It doesn't happen on MacOS VO as far as I can tell, but I will also check with another IOS version and master.

**Comment by loganbraywork** [comment]
@KatieWoe Confirms it happens on IOS 12

**Comment by loganbraywork** [comment]
Occurs on Master

**Comment by jessegreenberg** [comment]
Was able to confirm on my iPad with iPadOS 13

**Comment by zepumph** [comment]
After pairing with @jessegreenberg, we found that this is because on a mobile device, we aren't getting any events once the slider is at the end of the track. No `input` or `change` fires. On a keyboard, we still get the `keyup` event event if the value didn't change. So this alert will happen on devices that get the keyup, but not on iOS.

@jessegreenberg and I both this that this is alright behavior, and not vital to change. IIRC, the main reasoning for this "beyond edge" alert is to make sure to comminucate the boundary condition. On @jessegreenberg's iOS 13 VO iPad, we heard VO give a "bump" sound that signified the end of track, we also heard it re-read the aria-valuetext saying "left side of track." Marking for @terracoda and @emily-phet to comment on if we can publish without changing this logic. I will update documentation in `AccessibleValueHandler` to make sure the limitations of the supported alert are understood completely (even if we end up changing things later).

**Comment by terracoda** [comment]
Yep, I agree. The go-beyond-edge alert is meant to provide helpful state information when there is no change and an addition key press is made after reaching an edge. The information is not essential and should be available in the PDOM in the dynamic state descriptions for each of the mass spheres or in the dynamic part of the screen summary.

This should not block publication of the sim and does not need to be addressed.

**Comment by terracoda** [comment]
@zepumph, you can close this issue once you make the needed notation in `AccessibleValueHandler` . I have put a note in the Lessons Learned section of the Interactive Description design doc for GFLB.

**Comment by zepumph** [comment]
Excellent! We are ready to publish.

**Comment by loganbraywork** [comment]
For documentations sake, seems to occur in GFL a11y test as well
