### ISSUE TITLE
(Self-Voicing) Quick Menu? Design Help Needed

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#218]
@amanda-phet or @arouinfar, do you know of any quick menu - type design components
![Screen Shot 2020-07-29 at 12 40 06 PM](https://user-images.githubusercontent.com/1902116/88824820-643ed280-d1a1-11ea-8916-1d6f82c16fa9.png)

I am thinking that it would be a nice that when Self-Voicing is enabled by a leaner, that a small quick menu could appear on the sim screen with a few read-to-me options and quick access to the Self-Voicing Options to turning the feature off?

Maybe an expand/collapse box with a few buttons would work?

I think these 3 read-to-me buttons and an option to stop Self-Voicing would be nice:
1. Hint to get Started
2. Screen Summary
3. Key Details
4. Stop Self-Voicing or Self-Voicing Options

Any thoughts on how a quick menu should look in a PhET Sim?
Do you think an expand/collapse box is a possible way forward?
Or would a more traditional iconed menu bar be better?

This would be something that could eventually be enable in any sim with Self-Voicing, so I thought I would reach out for ideas.

**Comment by terracoda** [comment]
Based on Amanda's lovely icon, I put a very rough sketch in the last slide of this google slide stack
https://docs.google.com/presentation/d/1Koh72FrkzbCbhPdByvDFcRaMpc6iwZpa41b-ni7CGKA/edit#slide=id.g8d353e931b_0_0

**Comment by arouinfar** [comment]
Is the proposal to include this icon/AccordionBox in the sim itself?
<img src="https://user-images.githubusercontent.com/8419308/88852579-b5ec5a80-d1ab-11ea-81d4-9c24a8ba2ae4.png" width=300>

Sims often have space constraints, and we generally wouldn't put this sort of control in the sim. I think the navbar or PhET menu would be the more appropriate place.

The controls for Self-Voicing are already in the Options menu. Could some of this information be housed there?
![image](https://user-images.githubusercontent.com/8419308/88852321-568e4a80-d1ab-11ea-8886-f824d53ed32b.png)

I think it would also be helpful for a developer to be a part of this discussion because they would better understand the implementation constraints and could advise on which solution(s) are most feasible.

**Comment by terracoda** [comment]
The Options Menu is temporary. We need a fuller discussion, yes, I agree.

**Comment by terracoda** [comment]
I'll try an accordion box for now.

**Comment by terracoda** [comment]
Something like this for now :-)
![Screen Shot 2020-07-29 at 6 47 27 PM](https://user-images.githubusercontent.com/1902116/88854560-083d7380-d1cc-11ea-939c-4b37fe33ea14.png)

**Comment by terracoda** [comment]
Closing this issue for now. Jesse and I will try an accordionbox for the time being.
