### ISSUE TITLE
(Self-Voicing) Clickable area on hoverable area on reading block are different

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#225]
In a recent interview with self-voicing feature, the participant commented that there was a big discrepancy between the clickable area that makes the readable block (for distance) self-voice and the hoverable area that makes the reading highlight appear.

In screenshot below, the reading highlight only shows up when hovering over the letter "m", where the participant can make the content self-voice along a larger area. 
<img width="665" alt="Screen Shot 2020-08-06 at 5 54 24 PM" src="https://user-images.githubusercontent.com/1902116/89579207-f08a6e80-d80d-11ea-80d3-42353f7f0d6f.png">

@jessegreenberg, I have noticed this difference in my own use as well.

**Comment by jessegreenberg** [comment]
In the above commit I made it so that a down event anywhere in the bounds of the target hit node will trigger speech.  I am not sure what happened in the interview because the highlight should show up any time the mouse is within the bounds (not just over the text/Node content). But hopefully this change will make it easier to hear speech. @terracoda can you please review?

**Comment by terracoda** [comment]
@jessegreenberg, this is better, and I think the clickable area need to extend to include the edge of the R speech bubble.

From teh PhET Team feedback some people tried to click on the R and nothing happened. I assume they clicked the part of the R speech bubble that is outside the box.

**Comment by jessegreenberg** [comment]
@terracoda that "R" is just a visual overlay on top of the interactive component and so it isn't clickable. For now would it be OK to move the "R" so that it is totally within the box so that there isn't a desire to click outside of it? The look and feel of this highlight is likely to change quite a bit anyway.

**Comment by jessegreenberg** [comment]
Discussed with @terracoda - OK to move the "R" inside of the rectangle for now.

**Comment by jessegreenberg** [comment]
The "R" was moved inside of the rectangular highlight bounds. @terracoda is there anything else to do for this issue?

**Comment by terracoda** [comment]
This is good @jessegreenberg! Closing.
