### ISSUE TITLE
User request: 3 decimal places

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gravity-force-lab-basics#272]
> I have some feedback about the Gravity Force Lab Basics.  First I love the simulations and really like this lab both as it's regular version and this basics version.  One thing about the basics version is I would like to see more decimal places for the force like it is in the Coulomb's Law simulation.  The values going out to three decimal places would allow calculations done off of the values to be more accurate and allow students to better see the inverse square relationship with the distance.

This might be something to consider in a query parameter for GFL:B?

**Comment by arouinfar** [comment]
This is an interesting request. I tested a few different scenarios in GFLB to (a) calculate G from the shown m, r, and F values and (b) calculate F using a textbook value of G (6.67E-11) and the values of m and r shown in the sim. I'm not seeing any major precision issues in this data set.

| Scenario | Calculated G (m^3/kg*s) | Calculated F (N) |
| --- | --- | --- | 
| <img src="https://user-images.githubusercontent.com/8419308/112391616-cbc00a00-8cbd-11eb-9f19-3b291f00da0c.png" width=300> | 6.680E-11 | 33.350 | 
| <img src="https://user-images.githubusercontent.com/8419308/112391499-a03d1f80-8cbd-11eb-84bf-c84454d37f5e.png" width=300> | 6.672E-11 | 264.783 | 
| <img src="https://user-images.githubusercontent.com/8419308/112391913-3cffbd00-8cbe-11eb-9fa8-827d5cb9d2e0.png" width=300> | 6.678E-11 | 10.687 |

> The values going out to three decimal places would allow calculations done off of the values to be more accurate and allow students to better see the inverse square relationship with the distance.

Using data from the sim, I plotted F vs. 1/r^2 and the trendline is perfectly linear, so I don't agree. 
![image](https://user-images.githubusercontent.com/8419308/112393100-1fcbee00-8cc0-11eb-92cc-06510f64d515.png)

Since I'm not seeing any real issues with precision or the trendline, I don't think extra decimal places are necessary here. The mass and distance values in GFLB are purposely nonsensical so that the resulting force is on an order of magnitude more easily interpreted by younger learners. Adding extra decimal places is not something I would want to do for this population, but I recognize that this sim could potentially be used with older learners too. 

For the sake of flexibility, I wouldn't be opposed to adding an options dialog and query parameter like `?morePrecision` to increase the number of decimal places in the force to 3 (which is what we use in Coulomb's Law). However, to do this we would need to also update the descriptions. I imagine the extra digits in the force would be read out for free, but we would need to add descriptions for the options dialog. I don't think a small boost in flexibility is worth the time investment. I'd rather not defer this issue to ultimately close it a few years from now.

@oliver-phet please respond to the user and close. If this request comes up again, we can reopen this issue to reconsider.

**Comment by oliver-phet** [comment]
Thanks for digging into this, @arouinfar. I've replied to the user!
