### ISSUE TITLE
(Voicing) Voiced newton value does not always match visual newton value

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#274]
Something in the model is off because the voiced value for newtons does not always match the visually displayed value. I think this only happens when an increase in mass also results in a change in distance. This can happen when the spheres are "touching" and an increase in mass happens.

@jessegreenberg, you might what to check in with @zepumph on this one as I think we had to do some special work around for interactive description for this edge case.

**Comment by jessegreenberg** [comment]
I just played with the sim for a few minutes changing mass and constant size frequently. I tested the case where increasing the mass also increased the distance between spheres when they push each other away. I never heard a case where the force value did not match the visual text.

I am hoping that this has been fixed since this was reported in April, the Voicing has been fully re-implemented since then. @terracoda can you please test and verify that this has been fixed?

**Comment by terracoda** [comment]
This looks fixed :-) Thanks @jessegreenberg. Closing.
