### ISSUE TITLE
When moving 2 objects at once, should both have interactive highlights?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gravity-force-lab-basics#296]
**Test device**
iPad Air 2

**Operating System**
14.7.1

**Browser**
safari

**Problem description**
https://github.com/phetsims/qa/issues/702

On the iPad, when moving both spheres at the same time, only one is highlighted. Is that correct, or should both be highlighted at the same time?

**Steps to reproduce**
1. On an iPad, turn on interactive highlights in preferences
2. Move both spheres at the same time.

**Visuals**
https://drive.google.com/file/d/1iNdYQWMrN1hBgcEiSqkb9dBkeklypkQq/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity Force Lab: Basics‬
URL: https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.0-rc.2/phet/gravity-force-lab-basics_all_phet.html
Version: 1.1.0-rc.2 2021-08-30 16:27:03 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15
Language: en-us
Window: 1024x1228
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by jessegreenberg** [comment]
This is a really good question @Nancy-Salpepi, one that I would like to discuss with @emily-phet and @terracoda. Currently, our Highlight system supports only one highlight at a time. This came from the fact that the highlight system initially assumed focus highlights. It seems like it should be improved to support multiple highlights at once for cases of multitouch.

But I would like to see if others agree and then discuss when that should be done.

**Comment by jessegreenberg** [comment]
Discussed with Voicing team:

@emily-phet mentioned that enabling multiple Interactive Highlights at once, it could create complications when working with other types of highlights.

@terracoda suggested that there are sims coming up (like ratio-and-proportion and quadrilateral) that have multitouch fundamentally part of the intended interaction. When we work on those that would be a good time to revisit this.

@zepumph mentioned there may be issues with Interactive Highlights in Friction that may require further work more quickly.

@terracoda said that multitouch with Interactive Highlights might not work well with Voicing because the speech output will only read the last interaction. Maybe we should provide help content for users/teachers to describe this.

**Comment by jessegreenberg** [comment]
This has been noted by the team, but the result from the above discussion is that there is nothing to do for now or for this release of GFL:B. This issue can be closed and if we may want to support multiple highlights in the future we will create a new issue in scenery.
