### ISSUE TITLE
MassControl voicing should run on Voicing trait in NumberPicker

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab-basics#320]
I made [this commit](https://github.com/phetsims/gravity-force-lab-basics/commit/aa60ff35c871eeda5b2a6cfc0dcd8088ce750230) over in https://github.com/phetsims/scenery-phet/issues/725, which @terracoda used to report that context responses were lost in https://github.com/phetsims/scenery-phet/issues/725#issuecomment-1059757907.

I think we should have all voicing covered by the trait.

**Comment by zepumph** [comment]
@jessegreenberg, can you take a look, does this seem acceptable to you?

**Comment by terracoda** [comment]
The Mass number pickers in GFLB and the Left and Right Value number pickers in RaP are working well, and seem to be working in the exact same way as well.

The reading blocks are different, but that is intentional. The Mass Control reading blocks in GFLB are not keyboard accessible (this is intentional) whereas the Current Challenge reading block is keyboard accessible (this is intentional).

**Comment by terracoda** [comment]
Leaving open for @jessegreenberg.

**Comment by terracoda** [comment]
My comment was supposed to go in the related phetsims/scenery-phet#725 issue, copying it over there.

**Comment by jessegreenberg** [comment]
Code changes look good and @terracoda confirmed that the behavior is good, closing.
