### ISSUE TITLE
How are the number tweakers represented in HTML?

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#62]
@jessegreenberg, how are the number tweakers represented in HTML. Are they un-editable spinboxes?

And, I notieced that when I listen with the GFLB sim on phetest right now, I get something very strange. 

Instead of hearing about an input or an un-editable input, I get a whole list of the controls that follow (checkboxes and reset).

Just wondering if there might be a code error or a missing closing tag somewhere?

**Comment by jessegreenberg** [comment]
@terracoda the NumberPickers are represented with
```html
<input id="270-333-402-381-380-379-365" tabindex="0" min="1000000000" max="10000000000" type="number" style="width: 1px; height: 1px;">
```

When  I listen to this with NVDA, I hear
"Spin button, edit, selected 6 billion."

@terracoda is this just on initial readthrough?

**Comment by terracoda** [comment]
What you hear in NVDA sounds correct, but I am not hearing anything like that in VoiceOver with Safari.

Can you validate the code in the PDOM to see if there are any missing closing tags?

**Comment by terracoda** [comment]
@jessegreenberg , I was tabbing through, just to hear the interactive items when I got the funny read out.

**Comment by jessegreenberg** [comment]
@terracoda I just verified it sounds very weird on Safari. Perhaps it is because the number inputs currently have no label?

I did verify the HTML - All I see are warnings that our number inputs should have aria-valuemax and aria-valuemin...but I am not sure if I trust that since we are using a native input element with min and max values already.

**Comment by jessegreenberg** [comment]
Adding labels fixes the problem...mostly. I have each a label of "Mass Control". Now I am hearing something very weird  in VoiceOver. When NumberPicker receives focus, VoiceOver says:

", Mass (misspelled) Contr contents selected, Mass Control, incrementable edit text."

**Comment by jessegreenberg** [comment]
Here is the HTML
```html
<div tabindex="-1" id="container-270-333-402-381-380-379-365">
    <label tabindex="-1" id="label-270-333-402-381-380-379-365" for="270-333-402-381-380-379-365">Mass Control</label>
    <input id="270-333-402-381-380-379-365" tabindex="0" min="1000000000" max="10000000000" value="2000000000" type="number" style="width: 1px; height: 1px;">
</div>
```

**Comment by jessegreenberg** [comment]
While playing with other examples online,  I see that the input number text receives selection on focus. I think this is where "selection" is coming from, but we don't want this because direct number input will not be supported by this UI element.

Maybe we should do something more like:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuemin_attribute

**Comment by jessegreenberg** [comment]
Or maybe ARIA spinbutton?
https://www.w3.org/TR/wai-aria-1.1/#spinbutton

**Comment by jessegreenberg** [comment]
spinbutton role would be perfect. When focus lands on a spinbutton, I hear 
"4 billion, Mass control, stepper"

...but VoiceOver doesn't read the new value when aria-valuenow changes. I tried to use aria-valuetext because apparently aria-valuetext is supposed to be read instead of aria-valuenow when specified (according to https://www.w3.org/TR/wai-aria-1.1/#aria-valuenow). But still  no luck. I verified this problem outside of the simulation.

Here is the HTML for the spinbutton:
```html
<div id="270-333-402-381-380-379-365" tabindex="0" aria-label="Mass Control" role="spinbutton" aria-valuemin="1000000000" aria-valuemax="10000000000" aria-valuenow="10000000000"></div>
```


@terracoda do you have any thoughts about how to proceed?

**Comment by terracoda** [comment]
@jessegreenberg re "having no label" in https://github.com/phetsims/gravity-force-lab-basics/issues/62#issuecomment-371293296. Yes, that could easily be the problem. With no label there is no accessible name for the sim control.

@jessegreenberg, yes, we definitely want to use the role "spinbutton". I couldn't remember if it was role "spinbox" or something else. I was going to look it. Thanks for beating me to it.

As for the labeling technique, we do have some on screen text, "Mass 1". `aria-label` is usually used when there is no on screen text. When there is on screen text, I would lean towards using a traditional label element. 

In this case, however, the on-screen content only says "Mass 1", and we likely need more than that, (Mass 1 Size, maybe) so `aria-label` may be more appropriate.

In any case (label, aria-label, or aria-labelledby), we need an accessible name.

**Comment by jessegreenberg** [comment]
Sounds good @terracoda, Ill give that a try tomorrow when I have access to VoiceOver.

**Comment by terracoda** [comment]
Thanks @jessegreenberg. 
I can also test with VoiceOver if the code is available on phet test or in a dev link.

**Comment by jessegreenberg** [comment]
We tried the example @terracoda  provided in https://github.com/phetsims/gravity-force-lab-basics/issues/62#issuecomment-371353990.

VoiceOver *does* read the value with that HTML. But aria-valuetext is not supported,  so  it just reads the value with no units.

**Comment by jessegreenberg** [comment]
We verified that VoiceOver does not support aria-valuetext with input type=number and role=spinbutton in https://jsfiddle.net/0zo1mp6v/3/.

**Comment by jessegreenberg** [comment]
We also just verified that aria-valuetext is still broken with VoiceOver when we remove the spinbutton role.

@terracoda based on this, what HTML do you think we should use? If we cannot use input type=number, and we cannot use role=spinbutton, does that leave us with something custom that uses aria-live?

**Comment by terracoda** [comment]
On first thought, yes, but does it work in NVDA and JAWS?

Could you add aria-orientation="vertical" to see if that helps at all?

I'm going to email the wai-w3c ig group mailing list to see if anyone has any advice.

**Comment by terracoda** [comment]
@jessegreenberg, I am reassigning to you to for comment and/or iteration.

**Comment by jessegreenberg** [comment]
> And I get the value, the units, the label, the role as "stepper", when I place focus on the input. Then the number values only are read out when I increase and decrease the value with the arrow keys.

@terracoda this is what I observed as well in https://github.com/phetsims/gravity-force-lab-basics/issues/62#issuecomment-371658907. I assumed that for a science sim, it was not acceptable for VoiceOver to not read the units when the value changes. But maybe that is OK and a lesser evil than creating our own thing. Maybe we should discuss at a11y meeting today?

**Comment by terracoda** [comment]
@jessegreenberg, the numbers are long, so it might be ok not to repeat the unit. In this sim, there is only one unit for the spinbuttons. It is not like there are 3 spinbuttons with different units like there are sliders with different units in RIAW and OL.

I think you are right, we should ask what people think at the IDRC meeting, and also a content expert.

The unit is announced upon focus, which is good.

**Comment by jessegreenberg** [comment]
3/9/18:

We need to understand what JAWS does. But if the units are there on initial focus and can be easily found in help text, we are OK with using the semantics provided by ARIA (or native HTML), even though there is this VoiceOver issue.

**Comment by jessegreenberg** [comment]
Sounds great in JAWS, JAWS calls it a "spinbox" and always reads the units from aria-valuetext. But JAWS tells the user

"To set the value use the arrow keys  or type the value."

...which is not supported by our spinbox. @terracoda thoughts on what to do?

**Comment by jessegreenberg** [comment]
I think the ARIA specification clearly marks this as optional

> If the spinbutton text field allows directly editing the value, the following keys are supported:

IMO we shouldn't care too much about this, if user tries to type a value and nothing happens, they would probably try to use the arrow keys?

**Comment by jessegreenberg** [comment]
Another problem...JAWS reads all the 0s in the billions of kg. @terracoda do we need to modify the aria-valuetext to read "5 billion kilograms" instead of "5000000000" kilograms?

**Comment by terracoda** [comment]
Great that JAWS reads the control properly. 
We can provide our own helptext, so hopefully, that will take care of JAWS's default helptext.
Re the zeros, we should likely remove them. Hopefully Voice Over still reads out billion??

**Comment by jessegreenberg** [comment]
> We can provide our own helptext, 

I didn't realize this was possible, is there an aria attribute for this?

 > Re the zeros, we should likely remove them. Hopefully Voice Over still reads out billion??

I believe it should, we will end up replacing the number with the actual word "billion".

**Comment by terracoda** [comment]
By our own help text I just mean our own on-demand help text description in the PDOM. I didn't mean to imply that we can over-write JAWS's auto help text. A user would likely get both.

Screen reader help text can be turned off. I turn it off in Voice Over as I find it very annoying.

It's possible that aria-describedby or aria-role description could be used to over-ride auto screen reader help text. We would have to test. Based on previous research, however, I think in most cases we only need/want to provide on-demand help text.

**Comment by jessegreenberg** [comment]
Ok, thanks @terracoda that sounds great.

**Comment by jessegreenberg** [comment]
Assigning to myself to review and see if any further changes are necessary.

**Comment by jessegreenberg** [comment]
It sounds like the only remaining thing to do is convert "5000000000" kilograms to "5 billion killigrams" for the AT readout.

**Comment by jessegreenberg** [comment]
JAWS still reads "4 zero zero zero zero zero zero zero......" instead of "4 billion", even after the change. Similarly, VoiceOver reads "4000000000" instead of "4 billion kg" when the value changes. So JAWS and VoiceOver do not read aria-valuetext on input type number (or text) with aria-role=spinbutton.

**Comment by jessegreenberg** [comment]
@terracoda @emily-phet is it OK that JAWS reads all the zeros every change?

If that is OK, we are done with this issue.

If not, we could try a custom solution that uses aria-live to read the values at the right time with units, at least until AT can handle this.

I am starting to wonder if we should start using a custom approach for anything more than the most basic HTML/ARIA. It am realizing it would take far less time to "roll our own" than it does to troubleshoot ARIA every time we have to use it.

**Comment by emily-phet** [comment]
@terracoda @jessegreenberg 

Let's see if I'm understanding this correctly:

The spinboxes are implemeted with the slider input range spanning 1,000,000-10,000,000. The units are "billion kg".

In VoiceOver: you hear the slider value, but no units.

In JAWS: you hear the units (billion kg), and the slider value (1,000,000-10,000,000 - reading all zeros), but also some automatic help text that indicates number entry - that isn't actually possible in our implementation.

NVDA: reads number and units just fine?

How about this: Instead of having slider input range be 1,000,000-10,000,000 - what if it went from 1-10? I think technically this is how it should be anyway, since the unit is listed as "billion kgs". Then I would expect that the behavior would be the following:
VO: hear slider value (1-10) and folks will have to infer these are "billion kgs" based on the label text read out when first tabbing to spinbox
JAWS: hear slider value 1-10 with unit billion kg.
NVDA: ?

Is there a major issue with this approach that I'm not considering?

**Comment by jessegreenberg** [comment]
@emily-phet, mostly correct. We are already trying to make it say "1 billion kg", not "1,000,000,000 billion kg". There is also a difference between initial focus and first interaction. Here is a rundown of what it (mostly) sounds like.

- JAWS:
  - On focus: "1 billion kg, Mass 1 spin button, value selected"
  - On value change: "2 zero zero zero zero zero zero zero zero zero, value unselected""
- VoiceOver:
  - On focus: "1 billion kg, Mass 1 spin button,  value selected"
  - On value change: "2 billion" (readout display shows 2,000,000,000 but VO auto converts to billion)
- NVDA:
  - on focus: "1 billion kg, Mass 1 spin button, value selected"
  - On value change; "2 billion kg, value unselected"

We hear "selected" and "unselected" because the browser automatically highlights (or selects) the value for number input on focus, like this:
![capture](https://user-images.githubusercontent.com/6396244/37785853-cf241b32-2dc0-11e8-93dd-2dd9ca1638e5.PNG)

We are using `aria-valuetext` to convert 1,000,000,000 to read as "1 billion kg". PhET's NumberPicker uses a similar strategy for the visual display. VO and JAWS only read this text on initial focus. The input value of the spin button is the actual model value in kg. We could change the model to track mass in billions of kg, but that would require changing the calculations throughout. We would also have to do this in every sim that uses this formatting feature of NumberPicker.

If the above readout is not OK, I would recommend a custom solution. We can still use the "spinbutton" role to do this (it will not say "application", but it would not use an HTML input. This will read the same readout with units on all platforms, and remove the "selected" portion which does not apply to PhET. The cons include a solution that is non-standard and requires more JavaScript.

**Comment by jessegreenberg** [comment]
I went ahead and added something custom. It sounds great on VO and JAWS. For both:
On focus: "Mass 1, spin button, 1 billion kg"
On value change: "2 billion kg"

Will update comment after testing with VO.

**Comment by terracoda** [comment]
@jessegreenberg by "custom" do you mean you are using a `div role="spinbutton"` element  instead of an `input role="spinbutton"`?

I asked Bryan Garaventa for adnice on our non-editable spinbutton, and he suggested the following:
- use a non-editable element like a `div` or `span`
- with `tabindex="0"`
- plus `aria-readonly=”true”`
- plus `role=”spinbutton”` and all the other required ARIA attributes for that role such as 
- `aria-valuenow` and and optionally `aria-valuetext` (not optional for us, I think) to announce a string value when updated
- Then capture onKeyDown for the element and return false to prevent native processing.
According to Bryan, "This should allow incrementing using the arrow keys without passing values directly to the focusable element."

@jessegreenberg, are you doing all these things, thus far in the "custom" solution? Do yo think any of these tips would improve the interaction?

**Comment by terracoda** [comment]
Taking a stab in the dark here:
```html
     <label for="mass-01-spinbutton">Mass Control 1</label>
    <div id="mass-01-spinbutton" tabindex="0" aria-readonly=”true” role="spinbutton"  min="1" max="10" aria-valuenow="2" aria-valuetext="2 billion kg" >billion kg</div>
```
I'm not sure of the best method to label this control? Using aria-labeledby might be better?

```html
     <h3 id="mass-01-spinbutton-label">Mass Control 1</h3>
    <div id="mass-01-spinbutton" tabindex="0" aria-readonly=”true” role="spinbutton"  min="1" max="10" aria-valuenow="2" aria-valuetext="2 billion kg" aria-labeledby="mass-01-spinbutton-label">billion kg</div>
```

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/gravity-force-lab-basics/issues/62#issuecomment-377265007 is almost exactly what we are doing, with just two differences.
- We are using a `button` instead of a `div` because NVDA and maybe others don't focus the 'div role=spinbutton' when reading with the virtual cursor. `div role=spinbutton` only works with tab key.
- I am not using `aria-readonly` because I thought that indicated that the value was not changeable. We can add it if you think that is correct @terracoda, but I am skeptical. Here are the first sentences  of the specification.

> aria-readonly (property)§
Indicates that the element is not editable, but is otherwise operable. See related aria-disabled.
>This means the user can read but not set the value of the widget.

**Comment by terracoda** [comment]
@jessegreenberg, I think the specs language is not clear. 

It first says, "is not editable, but is otherwise operable" and then is says, "can read but not set the value."

Its possible that you/we are reading it too narrowly. 

One may need to consider the actual element that is being set to be readonly. There are two ways to edit and operate a `spinbutton`.  In the case of a typical `spinbutton` its value can be edited with direct input AND by using the arrow keys.

The meaning of "not set the value" might be restricted to not setting the value with direct input. Otherwise,  is the only benefit of `aria-readonly` for `spinbutton` is to be able to copy the text. That seems a bit limiting.

I think it is worth trying out "aria-readonly" attribute.

Regarding using the `button` element with `role="spinbutton"` seems a bit strange to me. It is great that it works, but I'm not sure what impact this would have across AT. The mixing of roles might not be totally future-proof (i.e., may not degrade gracefully). I'd like to investigate this further.

**Comment by terracoda** [comment]
@jessegreenberg, I just set-up two static examples for `spinbutton`, I get code error for the `button` example:
- Bad value spinbutton for attribute role on element button.
- Attribute aria-valuemin, aria-valuemax, aria-valuenow, aria-valuetext  not allowed on element button at this point.

Using invalid HTML to get the visual keyboard focus highlight when the cursor keys move virtual focus to a custom element is not a solid solution. The management of visual keyboard focus when a user is using the cursor keys is a separate issue, and one I am not sure has a solution.

Using valid HTML is quite critical for consistency across AT, so could you please re-implement with a div element? 

I'll upload my static examples. It is interesting that they both sound the same in VoiceOver.

**Comment by terracoda** [comment]
@jessegreenberg, here are the two examples I tested over in the a11y-research repo: [spinbutton examples](https://htmlpreview.github.io/?https://github.com/phetsims/a11y-research/blob/master/html-sketches/spinbutton/spinbutton-examples.html).

**Comment by terracoda** [comment]
@jessegreenberg, I added the label type:bug, but I am not sure that's the best label.

Please re-assign to me if you have more questions.

**Comment by jessegreenberg** [comment]
> Using valid HTML is quite critical for consistency across AT, so could you please re-implement with a div element?

@terracoda yes I can do this, but just to clarify, this will make it impossible to discover the element with the virtual cursor (at least on NVDA). In this case, valid HTML is not supported by the AT. Are you OK with this?

**Comment by terracoda** [comment]
@jessegreenberg, do you mean that 

1. `<div role="spinbutton">Mass 1</div> is not discoverable and perceivable with the Arrow keys at all?, or
2. the `spinbutton` is not operable and therefore not editable with arrow keys when `aria-readonly="true"` is added to the element?

For case 1, this has to be an NVDA bug.

**Comment by terracoda** [comment]
That is the weirdest bug, and I would think it would be high-priorty.
I just got an email from Quentin from NVDA today.

How do you normally submit bugs?

And regarding your question, since this sim is slated for release asap, it might be better to go with a button, but we need to make it clear that this is not a solution we can rely on, and that we have to watch it and do a maintenance release as soon as we can fix it.

I am going to reach our to the WCAG list for advice.

**Comment by jessegreenberg** [comment]
Ahh, @terracoda it looks like this was a problem in NVDA 2017.4, but not in NVDA 2018.1.1, which was released last week! Latest NVDA does support this! In that case it is definitely best to use a `div`.

**Comment by terracoda** [comment]
@jessegreenberg , awesome news!

**Comment by terracoda** [comment]
Would you mind trying out the` aria-readonly` attribute if you haven't already. If it only prevents text-editing capabilities, I think it is worth implementing. 

If it causes any other headaches, I can get clarification from an ARIA expert.

**Comment by jessegreenberg** [comment]
Sure Ill give it a try! I am running into an issue with VoiceOver now, VoiceOver doesn't read the inner content on the `<div role="spinbutton">Mass 1 Control</div>`. @terracoda should we have a duplicate accessible name for VoiceOver? Actually,  I think that is what you were suggesting above:

```html
<h3 id="mass-01-spinbutton-label">Mass Control 1</h3>
    <div id="mass-01-spinbutton" tabindex="0" aria-readonly=”true” role="spinbutton"  min="1" max="10" aria-valuenow="2" aria-valuetext="2 billion kg" aria-labelledby="mass-01-spinbutton-label">billion kg</div>
```

**Comment by jessegreenberg** [comment]
Using `aria-labelledby` makes it sounds nice in VoiceOver @terracoda.

**Comment by jessegreenberg** [comment]
I tried aria-readonly with NVDA and Firefox. the attribute doesn't change how the element is announced, but it **does** change how the AT enters forms mode. With `aria-readonly` the only way to change the value is by pressing insert+n+spacebar to force forms mode. Without `aria-readonly`, NVDA enters forms mode on tab focus, and after pressing "enter" if navigating with the virtual cursor.

@terracoda thoughts?

**Comment by terracoda** [comment]
@jessegreenberg, this required forcing of forms mode does not seem so user friendly. I think it is likely better for users if we leave that off for now, and see what users do with the `spinbutton`. We'll have to keep an eye on how JAWS users interpret the default JAWS help text about editing the text. Hopefully, that information will not get in the way of their interaction. If and when it does we can reconsider things.

**Comment by jessegreenberg** [comment]
@terracoda working on this now, going to test it everywhere just to make sure. I think that sounds good (minus the use of aria-readonly).

**Comment by jessegreenberg** [comment]
Got the above working,  sounds excellent in VO with Safari, NVDA and JAWS with FF 60! No longer using aria-live as a workaround. Great work @terracoda! I am going to commit it here soon.

**Comment by jessegreenberg** [comment]
@terracoda can you please give it a listen? If all sounds well I think this issue can be closed.

**Comment by terracoda** [comment]
@jessegreenberg thanks! I'll test and report back tomorrow.

**Comment by jessegreenberg** [comment]
Number tweakers have been generally implemented and fixed up  in https://github.com/phetsims/area-model-common/issues/150, I think this issue can be closed.
